services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    restart: unless-stopped
    environment:
      PRIMARY: ${PRIMARY}
      REPLICAS: ${REPLICAS}
      FULL_SYNC: true
      RUN_GRAVITY: true
      TZ: America/New_York
      CRON: 0 */6 * * *

