# coredns/docker-compose.yml
services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    volumes:
      - ./Corefile:/Corefile
    command: -conf /Corefile
    network_mode: "host"
    restart: unless-stopped
    env_file: .env
    environment:
      - DOMAIN=${DOMAIN}
      - COREDNS_BIND_IP=${COREDNS_BIND_IP}
