# glance/docker-compose.yml
services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      # Optionally, also mount docker socket if you want to use the docker containers widget
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./homelab-caddy-root.crt:/usr/local/share/ca-certificates/homelab-caddy-root.crt:ro
    env_file: .env
    networks:
      - caddy-net
    entrypoint: >
      sh -c "if [ -f /usr/local/share/ca-certificates/homelab-caddy-root.crt ]; then
                grep -qxF \"$(cat /usr/local/share/ca-certificates/homelab-caddy-root.crt)\" /etc/ssl/certs/ca-certificates.crt || \
                cat /usr/local/share/ca-certificates/homelab-caddy-root.crt >> /etc/ssl/certs/ca-certificates.crt;
              fi;
              exec \"$0\" \"$@\""
    command: ["/app/glance", "--config", "/app/config/glance.yml"]

networks:
  caddy-net:
    external: true
