- name: Homelab
  hide-desktop-navigation: false
  columns:
    - size: small
      widgets:
      - $include: ../widgets/beszel-stats.yml
      - $include: ../widgets/tailscale-stats.yml

    - size: full
      widgets:
        - type: docker-containers
          title: Homelab
          running-only: false
          hide-by-default: false
          containers:
            nebula-sync:
              name: Nebula Sync
              description: Pi-hole config sync
              icon: sh:sync-in-light
              hide: false
            caddy:
              name: Caddy
              description: Reverse proxy
              icon: si:caddy
              hide: false
            paperless-webserver-1:
              id: paperless
              name: Paperless-ngx
              description: Document OCR manager
              icon: si:paperlessngx
              hide: false
            paperless-broker-1:
              parent: paperless
              name: Redis
              hide: false
            paperless-db-1:
              parent: paperless
              name: Postgres
              hide: false
            karakeep-web-1:
              id: karakeep
              name: Karakeep
              description: Bookmark manager
              icon: auto-invert sh:karakeep
              hide: false
            karakeep-meilisearch-1:
              parent: karakeep
              name: Meilisearch
              hide: false
            karakeep-chrome-1:
              parent: karakeep
              name: Chrome
              hide: false
            coredns:
              name: CoreDNS
              description: Container DNS server
              icon: si:nextdns
              hide: false
            glance:
              name: Glance
              description: Homelab dashboard
              icon: sh:glance-light
              hide: false
            syncthing:
              name: Syncthing
              description: File sync tool
              icon: si:syncthing
              hide: false
            obsidian:
              name: Obsidian
              description: KB note-taking app
              icon: si:obsidian
              hide: false
            ollama:
              name: Ollama
              description: Local LLM server
              icon: si:ollama
              hide: false
            bentopdf:
              name: BentoPDF
              description: PDF conversion service
              icon: sh:bentopdf-light
              hide: false
            vaultwarden:
              name: Vaultwarden
              description: Password manager
              icon: si:vaultwarden
              hide: false
            beszel-hub:
              name: Beszel Hub
              description: System monitoring hub
              icon: sh:beszel-light
              hide: false
            beszel-agent:
              name: Beszel Agent
              description: System monitoring agent
              icon: sh:agent-zero-light
              hide: false
        - type: docker-containers
          title: Homelab Media
          sock-path: tcp://${MEDIA_IP}:2375
          running-only: false
          hide-by-default: false
          containers:
            jellyfin:
              name: Jellyfin
              description: Media server
              icon: si:jellyfin
              hide: false
            bazarr:
              name: Bazarr
              description: Media subtitle manager
              icon: sh:bazarr-light
              hide: false
            lidarr:
              name: Lidarr
              description: Music collection manager
              icon: sh:lidarr-light
              hide: false
            sonarr:
              name: Sonarr
              description: TV series manager
              icon: sh:sonarr-light
              hide: false
            radarr:
              name: Radarr
              description: Movie collection manager
              icon: sh:radarr-light
              hide: false
            prowlarr:
              name: Prowlarr
              description: Indexer manager
              icon: sh:prowlarr-light
              hide: false
            qbittorrent:
              name: qBittorrent
              description: BitTorrent client
              icon: sh:qbittorrent-light
              hide: false
            docker-socket-proxy:
              name: Docker Socket Proxy
              description: Filtered Docker API proxy
              icon: sh:haproxy-light
              hide: false
            gluetun:
              name: Gluetun
              description: Container VPN client
              icon: si:openvpn
              hide: false
            cleanuparr:
              name: Cleanuparr
              description: Media cleanup tool
              icon: sh:relaticle-light
              hide: false
            beszel-agent:
              name: Beszel Agent
              description: System monitoring agent
              icon: sh:agent-zero-light
              hide: false
        - type: docker-containers
          title: Homelab Compute
          sock-path: tcp://${COMPUTE_IP}:2375
          running-only: false
          hide-by-default: false
          containers:
            jupyter-pytorch:
              name: Jupyter Notebook
              description: Computing environment
              icon: si:jupyter
              hide: false
            wolf:
              name: Wolf
              description: Gaming container
              icon: sh:steam-light
              hide: false
            kokoro-fastapi:
              name: Kokoro-FastAPI
              description: OpenAIâ€‘compatible TTS server
              icon: si:stackexchange
              hide: false
            n8n:
              name: n8n
              description: Workflow automation tool
              icon: si:n8n
              hide: false
            glance:
              name: Glance
              description: Compute homelab dashboard
              icon: sh:glance-light
              hide: false
            ollama:
              name: Ollama
              description: Local LLM server
              icon: si:ollama
              hide: false
            open-webui:
              name: Open WebUI
              description: Local LLM chat WebUI
              icon: sh:open-webui
              hide: false
            wolf:
              name: Wolf
              description: Gaming container manager
              icon: sh:gamepad-light
              hide: false
            docker-socket-proxy:
              name: Docker Socket Proxy
              description: Filtered Docker API proxy
              icon: sh:haproxy-light
              hide: false
            beszel-agent:
              name: Beszel Agent
              description: System monitoring agent
              icon: sh:agent-zero-light
              hide: false

    - size: small
      widgets:
      - $include: ../widgets/immich-stats.yml
      - $include: ../widgets/jellyfin-stats.yml
      # - $include: ../widgets/gluetun-stats.yml
      - $include: ../widgets/karakeep-stats.yml
      - type: releases
        cache: 6h
        show-source-icon: true
        collapse-after: 5
        limit: 20
        repositories:
          - Tecnativa/docker-socket-proxy
          - alam00000/bentopdf
          - remsky/Kokoro-FastAPI
          - tailscale/tailscale
          - jellyfin/jellyfin
          - Sonarr/Sonarr
          - Radarr/Radarr
          - Lidarr/Lidarr
          - Prowlarr/Prowlarr
          - Cleanuparr/Cleanuparr
          - qbittorrent/qBittorrent
          - home-assistant/core
          - glanceapp/glance
          - open-webui/open-webui
          - immich-app/immich
          - syncthing/syncthing
          - n8n-io/n8n
          - pi-hole/pi-hole
          - ollama/ollama
          - ClassicOldSong/Apollo
          - ClassicOldSong/moonlight-android
          - microsoft/powertoys
          - dani-garcia/vaultwarden
          - paperless-ngx/paperless-ngx
          - karakeep-app/karakeep
          - sst/opencode
          - eoyilmaz/displaycal-py3
